version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: springboot-app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: nomis
      POSTGRES_PASSWORD: aa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
